### ISSUE TITLE
コースアウトしたプレイヤーの衝突について

### ISSUE THREAD

**Issue by RyoAshida** [takashi-chikayama/software-for-SamurAI-Coding-2018-19#1]
official/raceState.cpp におけるコースアウトと衝突の処理ですが，コースアウトしたプレイヤーがいる場合には衝突判定を行っていません（動線が点になるのではなく消失しています）．コースアウトしたプレイヤーのいるマスにもう一方のプレイヤーが移動することができ，この場合，それ以降両者が衝突し続けることになります．これは意図した動作でしょうか？

**Comment by task-h** [comment]
ご指摘ありがとうございます．バグですので，ソフトウェアを修正いたします．

**Comment by task-h** [comment]
修正版をcommitしました．
