### ISSUE TITLE
AIの残り思考時間について

### ISSUE THREAD

**Issue by yamatchan** [takashi-chikayama/software-for-SamurAI-Coding-2018-19#2]
ゲーム管理システム(official)にて，AIの残り思考時間が2重に減算される症状が発生しています．
具体的には，nターン目の減算時に，n-1ターン目とnターン目の思考時間が減算されています．

-- ログの例 --
[system] Try: hand shake
[system] spend time: 336, remain: 36664
[system] Success!: hand shake
[system] ================================
[system] turn: 0
[system] spend time: 172, remain: 36828
[system] ================================
[system] turn: 1
[system] spend time: 125, remain: 36531
[system] ================================
[system] turn: 2
[system] spend time: 128, remain: 36278
[system] ================================
…

-- 残り時間 --
[turn 0] 36828 = 37000 - 172
[turn 1] 36531 = 36828 - (125 + 172)
[turn 2] 36278 = 36531 - (128 + 125)
…

**Comment by takashi-chikayama** [comment]
はい、確認します。たぶん今週末。

近山

2019年1月31日(木) 17:35 Yamatchan <notifications@github.com>:

**Comment by takashi-chikayama** [comment]
すいません、昨日今日と時間がとれなくて未済のままです。たぶん簡単なことだろうと思われるのですが。明日にでも対応します。

近山

2019年1月31日(木) 20:51 Takashi Chikayama <takashi.chikayama@gmail.com>:

**Comment by takashi-chikayama** [comment]
単純に2箇所で残り時間を減算していました。片方をコメントアウトしました。たぶんこれで解決できたでしょう。
Git push しました。

近山

2019年2月3日(日) 23:32 Takashi Chikayama <takashi.chikayama@gmail.com>:
