### ISSUE TITLE
同じステップ数なのに引き分けにならない場合がある

### ISSUE THREAD

**Issue by tanzaku** [takashi-chikayama/software-for-SamurAI-Coding-2018-19#3]
添付画像の通り、浮動小数点数の誤差により引き分けとならないことがあるようです。

![image](https://user-images.githubusercontent.com/284172/52637160-d5d58300-2f11-11e9-8039-1ae893c47b39.png)

**Comment by task-h** [comment]
確認，修正いたします．少なくとも予選・決勝の勝敗には影響がでないよう処理いたします．

**Comment by takashi-chikayama** [comment]
ご連絡ありがとうございます。たぶん許容誤差を設定することで大丈夫でしょう。明日までにはなんとかします。

近山

2019年2月13日(水) 9:36 Tasuku HIRAISHI <notifications@github.com>:

**Comment by task-h** [comment]
ゲームソフトウェアは両者のゴールタイムを出力するのみで勝敗判定は外部で行っていますので，本ソフトウェアのupdateは行わず，勝敗判定処理を修正することでこの問題が起こらないようにします．
